---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddCircleWebhookEditor"
  group: "atomist"
  artifact: "enrollment-rugs"
  version: "0.3.43"
  origin:
    repo: "git@github.com:atomisthq/enrollment-rugs.git"
    branch: "master"
    sha: "a27f45e"
  parameters:
    - "atomistWebhookUrl": "https://webhook.atomist.com/atomist/circle"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
editor:
  name: "AddCircleWebhookEditor"
  group: "atomist"
  artifact: "enrollment-rugs"
  version: "0.3.43"
  origin:
    repo: "git@github.com:atomisthq/enrollment-rugs.git"
    branch: "master"
    sha: "a27f45e"
  parameters:
    - "atomistWebhookUrl": "https://webhook.atomist.com/atomist/circle"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170830045005"
editor:
  name: "AddCircleWebhookEditor"
  group: "atomist"
  artifact: "enrollment-rugs"
  version: "0.3.55"
  origin:
    repo: "git@github.com:atomisthq/enrollment-rugs.git"
    branch: "sylvain/expose-add-atomist-webhook-command"
    sha: "af78e82*"
  parameters:
    - "atomistWebhookUrl": "https://webhook.atomist.com/circle"

