version: 2
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: '-Xmx3200m'
    steps:
      - run: >-
          curl
          -H 'Content-Type: application/json'
          -d '{"payload": {"lifecycle": "started", "build_num": "'${CIRCLE_BUILD_NUM}'", "vcs_revision": "${CIRCLE_SHA1}", "branch": "${CIRCLE_BRANCH}", "reponame": "${CIRCLE_PROJECT_REPONAME}", "username": "${CIRCLE_PROJECT_USERNAME}"}}'
          "https://httpbin.org/post"
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "pom.xml" }}'
            - v1-dependencies-
      - run: 'mvn dependency:go-offline'
      - save_cache:
          paths:
            - ~/.m2
          key: 'v1-dependencies-{{ checksum "pom.xml" }}'
      - run: mvn integration-test
notify:
  webhooks:
  - url: 'https://httpbin.org/post'
